# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-06-12 18:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatriculaGrupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academia.Grupo', verbose_name='Grupo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroDocumento', models.CharField(max_length=20, unique=True, verbose_name=' N\xfamero de Documento')),
                ('telefono1', phonenumber_field.modelfields.PhoneNumberField(default='+573040000000', max_length=128, verbose_name='Tel\xe9fono 1')),
                ('telefono2', phonenumber_field.modelfields.PhoneNumberField(default='+573040000000', max_length=128, verbose_name='Tel\xe9fono 2')),
                ('direccion', models.CharField(max_length=45, verbose_name='Direcci\xf3n')),
                ('ciudad', models.CharField(max_length=45, verbose_name='Ciudad')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramaAcademicoPerfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programaacademico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academia.ProgramaAcademico', verbose_name='Programa Acad\xe9mico')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
