# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-06-12 17:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('espaciofisico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripci\xf3n')),
                ('estado_activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50, unique=True, verbose_name='Descripci\xf3n')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=25, unique=True, verbose_name='Grupo')),
                ('estado_activo', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='GrupoAsignatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academia.Asignatura', verbose_name='Asignatura')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academia.Grupo', verbose_name='Grupo')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramaAcademico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=25, unique=True)),
                ('descripcion', models.CharField(max_length=50)),
                ('nivelformacion', models.CharField(choices=[('posgrado', 'Posgrado'), ('pregrado', 'Pregrado')], max_length=50, verbose_name='Nivel de formaci\xf3n')),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academia.Facultad', verbose_name='Facultad')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espaciofisico.Sede', verbose_name='Sede')),
            ],
        ),
        migrations.AddField(
            model_name='asignatura',
            name='programaacademico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academia.ProgramaAcademico', verbose_name='Programa Acad\xe9mico'),
        ),
    ]
