# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-07-07 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programaacademico',
            name='registroCalificado',
            field=models.TextField(blank=True, help_text='200 caracteres', max_length=200, null=True, verbose_name='Registro Calificado'),
        ),
        migrations.AlterField(
            model_name='programaacademico',
            name='codigo',
            field=models.CharField(max_length=25, unique=True, verbose_name='C\xf3digo SNIES'),
        ),
        migrations.AlterField(
            model_name='programaacademico',
            name='nivelformacion',
            field=models.CharField(choices=[('posgrado', 'Posgrado'), ('pregrado', 'Pregrado'), ('administrativo', 'Administrativo')], max_length=50, verbose_name='Nivel de formaci\xf3n'),
        ),
    ]
