# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-07-07 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0002_auto_20180707_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='programaacademico',
            name='estadoActivo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
