# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-06-24 01:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academia', '0001_initial'),
        ('recursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservacionLugar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=45, verbose_name='Descripci\xf3n')),
                ('fechaReserva', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Reservaci\xf3n')),
                ('fechaInicio', models.DateTimeField(verbose_name='Fecha de Inicio')),
                ('fechaFinalizacion', models.DateTimeField(verbose_name='Fecha de Finalizaci\xf3n')),
                ('observacionSolicitud', models.TextField(max_length=1000, verbose_name='Observaci\xf3n Solicitud')),
                ('observacionEntrega', models.TextField(max_length=1000, verbose_name='Observaci\xf3n Entrega')),
                ('observacionRecepcion', models.TextField(max_length=1000, verbose_name='Observaci\xf3n Recepci\xf3n')),
                ('estadoActivo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='recursos',
            name='recursoTecnologico',
            field=models.BooleanField(default=True, verbose_name='Recurso Tecnol\xf3gico'),
        ),
        migrations.AddField(
            model_name='reservacionlugar',
            name='Lugar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos.Recursos', verbose_name='Lugar'),
        ),
        migrations.AddField(
            model_name='reservacionlugar',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservacionlugar_docente', to=settings.AUTH_USER_MODEL, verbose_name='Docente'),
        ),
        migrations.AddField(
            model_name='reservacionlugar',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academia.Grupo', verbose_name='Grupo'),
        ),
        migrations.AddField(
            model_name='reservacionlugar',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
