# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-06-24 02:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recursos', '0002_auto_20180624_0101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservacionlugar',
            name='observacionEntrega',
        ),
        migrations.RemoveField(
            model_name='reservacionlugar',
            name='observacionRecepcion',
        ),
        migrations.AddField(
            model_name='reservacionlugar',
            name='funcionario',
            field=models.ForeignKey(blank=True, help_text='Funcionario que da cierre a prestamo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservacionlugar_Funcionario', to=settings.AUTH_USER_MODEL, verbose_name='Funcionario'),
        ),
        migrations.AlterField(
            model_name='reservacionlugar',
            name='descripcion',
            field=models.CharField(help_text='Nombre de la reservaci\xf3n, m\xe1ximo 45 caracteres', max_length=45, verbose_name='Descripci\xf3n'),
        ),
        migrations.AlterField(
            model_name='reservacionlugar',
            name='observacionSolicitud',
            field=models.TextField(blank=True, help_text='1.000 caracteres', max_length=1000, null=True, verbose_name='Observaci\xf3n Solicitud'),
        ),
    ]
