# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-06-24 02:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recursos', '0003_auto_20180624_0206'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioReservacionLugar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(blank=True, help_text='1.000 caracteres', max_length=500, null=True, verbose_name='Comentario')),
                ('reservacionLugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos.ReservacionLugar', verbose_name='Reservaci\xf3n de Lugar')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
