# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-06-28 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0004_comentarioreservacionlugar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarioreservacionlugar',
            name='comentario',
            field=models.TextField(blank=True, help_text='500 caracteres', max_length=500, null=True, verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='recursos',
            name='accesorios',
            field=models.TextField(blank=True, help_text='1.000 caracteres', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='recursos',
            name='caracteristicas',
            field=models.TextField(blank=True, help_text='1.000 caracteres', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='recursos',
            name='perifericos',
            field=models.TextField(blank=True, help_text='3.000 caracteres', max_length=3000, null=True, verbose_name='Perif\xe9ricos'),
        ),
    ]
