# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-06-29 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0005_auto_20180628_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='recursos',
            name='placaInventario',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Placa de Inventario'),
        ),
        migrations.AlterField(
            model_name='recursos',
            name='recursoTecnologico',
            field=models.BooleanField(default=False, verbose_name='Recurso Tecnol\xf3gico'),
        ),
    ]
