# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-06-12 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=25, unique=True, verbose_name='Descripci\xf3n')),
            ],
        ),
    ]
