# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-06-27 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espaciofisico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sede',
            name='estadoActivo',
            field=models.BooleanField(default=True, verbose_name='Estado Activo'),
        ),
    ]
